/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.system.ui;

import com.system.dao.BookingAvailabilityReportDao;
import com.system.dao.CourseDao;
import com.system.dao.DivisionDao;
import com.system.dao.GroupDao;
import com.system.dto.BookingAvailabilityDto;
import com.system.model.Course;
import com.system.model.Division;
import com.system.model.Group;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class BookingCourse extends javax.swing.JFrame {

    /**
     * Creates new form BookingCourse
     */
    public BookingCourse() {
        initComponents();
        setLocationRelativeTo(null);
        loadDataToComboBoxes();
    }

    private void loadDataToComboBoxes() {
        jComboBox2.addItem("Select");
        for (Division division : DivisionDao.loadToComboBox()) {
            jComboBox2.addItem(division.getName());
        }

        jComboBox1.addItem("Select");
        for (Course course : CourseDao.loadToComboBox()) {
            jComboBox1.addItem(course.getName());
        }

        jComboBox3.addItem("Select");
        for (Group group : GroupDao.loadToComboBox()) {
            jComboBox3.addItem(group.getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 180, 52));

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 180, 52));

        jPanel1.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 209, 53));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 40, 90, 30));

        jDateChooser2.setDateFormatString("yyyy-MMM-dd");
        jPanel1.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 50, 180, 50));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Division", "Group", "Course", "Availability"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 1010, 100));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 70, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String date = null;
        BookingAvailabilityReportDao bookingAvailabilityReportDao = new BookingAvailabilityReportDao();
        List<BookingAvailabilityDto> bookingAvailabilityDto = new ArrayList<>();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

        if (jDateChooser2.getDate() != null) {
            date = sdf.format(jDateChooser2.getDate());
        }

        String groupName = jComboBox3.getSelectedItem().toString();
        String courseName = jComboBox1.getSelectedItem().toString();
        String divisionName = jComboBox2.getSelectedItem().toString();

        int divisionId = divisionName.equals("Saturday") ? 1
                : (divisionName.equals("Sunday")) ? 2
                : 0;

        int groupId = groupName.equals("Morning") ? 1
                : (groupName.equals("Afternoon")) ? 2
                : (groupName.equals("Afternoon")) ? 3
                : 0;

        int courseId = courseName.equals("Yoha") ? 1
                : (groupName.equals("Zumba")) ? 2
                : (groupName.equals("Aquacise")) ? 3
                : (groupName.equals("Box Fit")) ? 4
                : (groupName.equals("Box Fit")) ? 5
                : 0;

        if (date != null && groupName.equals("Select") && courseName.equals("Select") && divisionName.equals("Select")) {
            bookingAvailabilityDto = bookingAvailabilityReportDao.filterByDate(date);
        } else if (date == null && !groupName.equals("Select") && courseName.equals("Select") && divisionName.equals("Select")) {
            bookingAvailabilityDto = bookingAvailabilityReportDao.filterByGroup(groupId);
        } else if (date == null && groupName.equals("Select") && !courseName.equals("Select") && divisionName.equals("Select")) {
            bookingAvailabilityDto = bookingAvailabilityReportDao.filterByCourse(courseId);
        } else if (date == null && groupName.equals("Select") && courseName.equals("Select") && !divisionName.equals("Select")) {
            bookingAvailabilityDto = bookingAvailabilityReportDao.filterByDivision(divisionId);
        } else if (date == null && !groupName.equals("Select") && courseName.equals("Select") && !divisionName.equals("Select")) {
            bookingAvailabilityDto = bookingAvailabilityReportDao.filterByDivisionAndGroup(divisionId, groupId);
        } else if (date == null && groupName.equals("Select") && !courseName.equals("Select") && !divisionName.equals("Select")) {
            bookingAvailabilityDto = bookingAvailabilityReportDao.filterByDivisionAndCourse(divisionId, courseId);
        } else if (date == null && !groupName.equals("Select") && !courseName.equals("Select") && !divisionName.equals("Select")) {
            bookingAvailabilityDto = bookingAvailabilityReportDao.filterByDivisionAndGroupAndCourse(divisionId, groupId, courseId);
        } else if (date != null && !groupName.equals("Select") && !courseName.equals("Select") && !divisionName.equals("Select")) {
            System.out.println(date);
            bookingAvailabilityDto = bookingAvailabilityReportDao.filterByAll(date, groupId, divisionId, courseId);
        }

        DefaultTableModel defaultTableModel = (DefaultTableModel) jTable1.getModel();
        Object rowData[] = new Object[5];
        for (int i = 0; i < bookingAvailabilityDto.size(); i++) {
            rowData[0] = bookingAvailabilityDto.get(i).getDate();
            rowData[1] = bookingAvailabilityDto.get(i).getDivisionName();
            rowData[2] = bookingAvailabilityDto.get(i).getGroupName();
            rowData[3] = bookingAvailabilityDto.get(i).getCourseName();
            rowData[4] = bookingAvailabilityDto.get(i).getAvailability();
            defaultTableModel.addRow(rowData);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jComboBox1.setSelectedItem("Select");
        jComboBox2.setSelectedItem("Select");
        jComboBox3.setSelectedItem("Select");
        DefaultTableModel dm = (DefaultTableModel) jTable1.getModel();
        dm.getDataVector().removeAllElements();
        dm.fireTableDataChanged();
        jDateChooser2.setDate(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookingCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
